apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orderdb
  name: orderdb
  namespace: salesorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderdb
  template:
    metadata:
      labels:
        app: orderdb
    spec:
      containers:
      - image: mysql/mysql-server:5.7.31   
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        volumeMounts:
        - name: orderdb-data
          mountPath: /var/lib/mysql
      volumes:
      - name: orderdb-data
        emptyDir: {}               