apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orderdb
  name: orderdb
  namespace: salesorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderdb
  template:
    metadata:
      labels:
        app: orderdb
    spec:
      containers:
      - image: mysql/mysql-server:5.7.31   
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:                # Read environment variables from kubernetes secrets
            secretKeyRef:
              name: mysql-login
              key: rootPassword
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-login
              key: database-name      
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-login
              key: username
        - name: MYSQL_PASSWORD      
          valueFrom:
            secretKeyRef:
              name: mysql-login
              key: password        
        volumeMounts:
        - name: orderdb-data
          mountPath: /var/lib/mysql
      volumes:
      - name: orderdb-data
        emptyDir: {}               