apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orderapi
  name: orderapi
  namespace: salesorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderapi
  template:
    metadata:
      labels:
        app: orderapi
    spec:
      containers:
      - image: orderapi
        name: orderapi
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: grpc
        env: # Environment variables supplied to the Pod
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-login
              key: database-name      
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-login
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-login
              key: password        
