apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: productdb
  name: productdb
  namespace: salesorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productdb
  template:
    metadata:
      labels:
        app: productdb
    spec:
      containers:
      - image: mcr.microsoft.com/mssql/server   
        name: sqlserver
        ports:
        - containerPort: 1433
          name: sqlserver
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
        volumeMounts:
        - name: productdb-data
          mountPath: /var/opt/mssql
      volumes:
      - name: productdb-data
        persistentVolumeClaim: 
          claimName: pvclaim               