apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: productapi
  name: productapi
  namespace: salesorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productapi
  template:
    metadata:
      labels:
        app: productapi
    spec:
      containers:
      - image: salesproductapi
        name: productapi
        imagePullPolicy: Never
        ports:
        - containerPort: 4999
          name: productapi
        env:
            - name: ASPNETCORE_ENVIRONMENT
              value: DEVELOPMENT
            - name: SQLSERVER_CONNECTIONSTRING
              value: "Server=productapi;Database=productApi;User=sa;Password=Mau123&&&;"

  
