apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: salesapiuser
  name: salesapiuser
  namespace: salesorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salesapiuser
  template:
    metadata:
      labels:
        app: salesapiuser
    spec:
      containers:
      - image: salesapiusernode
        name: salesapiuser
        imagePullPolicy: Never
        ports:
        - containerPort: 8088
          name: http          
        - containerPort: 50051
          name: grpc            