apiVersion: v1
kind: Service
metadata:
  labels:
    app: salesapiuser
  name: apiusergrpc
  namespace: salesorder
spec:
  type: NodePort    
  ports:
  - name: "apiusergrpc-service"
    port: 50051
    nodePort: 31005
  selector:
    app: salesapiuser  