apiVersion: v1
kind: Service
metadata:
  labels:
    app: orderapi
  name: orderapigrpc
  namespace: salesorder
spec:
  type: NodePort
  ports:
  - name: "orderapigrpc-service"
    port: 9092
    nodePort: 31009
  selector:
    app: orderapi   