apiVersion: v1
kind: Service
metadata:
  labels:
    app: orderweb
  name: orderweb
  namespace: salesorder
spec:
  type: NodePort
  ports:
  - name: "orderweb-service"    
    port: 80
    nodePort: 31008
  selector:
    app: orderweb  