apiVersion: v1
kind: Service
metadata:
  labels:
    app: productapi
  name: productapi
  namespace: salesorder
spec:
  ports:
  - name: "productapi-service"
    port: 4999
    targetPort: 4999
    protocol: TCP
  selector:
    app: productapi  