apiVersion: v1
kind: Service
metadata:
  labels:
    app: productdb
  name: productdb
  namespace: salesorder
spec:
  type: ClusterIP
  ports:
  - name: "productdb-service"    
    port: 1433
    targetPort: 1433
  selector:
    app: productdb  