apiVersion: v1
kind: Service
metadata:
  labels:
    app: productapi
  name: productapi
  namespace: salesorder
spec:
  type: NodePort    
  ports:
  - name: "productapi-service"
    port: 4999
    nodePort: 31003
  selector:
    app: productapi  