apiVersion: v1
kind: Service
metadata:
  labels:
    app: productdb
  name: productdb
  namespace: salesorder
spec:
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
  type: LoadBalancer
