apiVersion: v1
kind: Service
metadata:
  labels:
    app: salesapiuser
  name: salesapiuser
  namespace: salesorder
spec:
  type: NodePort    
  ports:
  - name: "salesapiusernode-service"
    port: 8088
    nodePort: 31000
  selector:
    app: salesapiuser  