apiVersion: v1
kind: Service
metadata:
  labels:
    app: productfrontend
  name: productfrontend
  namespace: salesorder
spec:
  type: NodePort
  ports:
  - name: "productfrontend-service"    
    port: 80
    nodePort: 31004
  selector:
    app: productfrontend  