apiVersion: v1
kind: Service
metadata:
  labels:
    app: salesapiuser
  name: apiuserhttp
  namespace: salesorder
spec:
  ports:
  - name: "salesapiusernode-service"
    port: 8088
    targetPort: 8088
    protocol: TCP
  selector:
    app: salesapiuser  