apiVersion: v1
kind: Service
metadata:
  labels:
    app: salesuserreact
  name: salesuserreact
  namespace: salesorder
spec:
  type: NodePort
  ports:
  - name: "salesuserreact-service"
    port: 3000
    nodePort: 31001
  selector:
    app: salesuserreact      