apiVersion: v1
kind: Service
metadata:
  labels:
    app: salesapiusernode
  name: salesapiusernode
  namespace: salesorder
spec:
  type: NodePort    
  ports:
  - name: "salesapiusernode-service"
    port: 8088
    targetPort: 8088
    nodePort: 8088
  selector:
    app: salesapiusernode  