apiVersion: v1
kind: Service
metadata:
  labels:
    app: userdb
  name: userdb
  namespace: salesorder
spec:
  type: ClusterIP
  ports: 
  - name: "userdb-service"
    port: 27017
    targetPort: 27017
  selector:
    app: userdb      