apiVersion: v1
kind:  Service
metadata:
  labels:
    app: webproductblazor
  name: webproductblazor
  namespace: salesorder
spec:
  type: NodePort
  ports:
  - name: "webproductblazor-service"  
    port: 80
    nodePort: 31007
  selector:
    app: webproductblazor  